service: lambda-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-north-1
  apiGateway:
    usagePlan:
      quota:
        limit: 100
        period: DAY
      throttle:
        burstLimit: 5
        rateLimit: 10
    apiKeys:
      - api-key


functions:
  word:
    handler: handler.word
    events:
      - http:
          path: /word
          method: post
          cors: true
          apiKeyRequired: true
          apiKeyId: api-key

plugins:
  - serverless-python-requirements
