service: lambda-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-north-1

functions:
  word:
    handler: handler.word
    events:
      - http:
          path: /word
          method: post
          cors: true

plugins:
  - serverless-python-requirements
