name: Deploy Lambda on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Serverless Framework and plugins
        run: |
          npm install -g serverless
          npm install serverless-python-requirements

      - name: Deploy Lambda function
        run: |
          serverless deploy --stage prod --region eu-north-1 --aws-profile default
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}